site_name: Mitja Jan훾i훾

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - content.tabs.link
    - navigation.top
    - navigation.sections
    - content.code.copy
    - navigation.path
    - toc.integrate
  language: en 
  icon:
    logo: simple/smart
  favicon: files/logo.png
  palette: 
    primary: black
  
copyright: Copyright &copy; 2024 Mitja Jan훾i훾

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/distractor

extra:
  social:
    - icon: simple/researchgate
      link: https://www.researchgate.net/profile/Mitja-Jancic
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.si/citations?user=pl8xsvMAAAAJ
    - icon: simple/orcid
      link: https://orcid.org/0000-0003-1850-412X
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/mitja-jan%C4%8Di%C4%8D-89710b133
    - icon: simple/github
      link: https://github.com/distractor
    - icon: simple/gitlab
      link: https://gitlab.com/mjancic


plugins:
  - glightbox
  - search
  - tags

extra_css:
  - stylesheets/custom.css

extra:
  analytics:
    provider: google
    property: G-DWFZQKWEGD
  consent:
    title: Cookie consent
    description: > # (1)
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.


nav:
  - Home: index.md
  - About me: about.md
  - Research: research.md
  - Publications: publications.md
  - Projects: projects.md
  - CV: CV.md